// take the entire object outside of component
// so the object will not be generated by js each time this component rerenders
const containerStyle = {
  // to place the elements side by side
  display: "flex",
  alignItems: "center",
  gap: "16px",
};

const starContainerStyle = {
  display: "flex",
  gap: "4px",
};

const textStyle = {
  lineHeight: "1",
  margin: "0",
};

// destruct the props object
// if maxRating doesn't exist, set a default value
// common way of setting default props
export default function StarRating({ maxRating = 5 }) {
  return (
    <div style={containerStyle}>
      <div style={starContainerStyle}>
        {/* don't care about the element but only the index, so use placeholder "_" */}
        {Array.from({ length: maxRating }, (_, i) => (
          <span>S{i + 1}</span>
        ))}
      </div>
      <p style={textStyle}>10</p>
    </div>
  );
}
